//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploT4
{
    using System;
    using System.Collections.Generic;
    
    /// Este es un comentario de prueba
    public partial class MaestroTipoHora
    {
        public int CodigoMaestro { get; set; }
        public int CodigoTipoHora { get; set; }
        public string Nombre { get; set; }
    
        public virtual TipoHora TipoHora { get; set; }
    }
}
