//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploT4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReporteDeTiemposIntergrupoPruebasEntities : DbContext
    {
        public ReporteDeTiemposIntergrupoPruebasEntities()
            : base("name=ReporteDeTiemposIntergrupoPruebasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MaestroTipoHora> MaestroTipoHoras { get; set; }
        public virtual DbSet<TipoHora> TipoHoras { get; set; }
    }
}
