//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploT4
{
    using System;
    using System.Collections.Generic;
    
    /// Este es un comentario de prueba
    public partial class TipoHora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoHora()
        {
            this.MaestroTipoHoras = new HashSet<MaestroTipoHora>();
        }
    
        public int CodigoTipoHora { get; set; }
        public string Nombre { get; set; }
        public bool Facturable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaestroTipoHora> MaestroTipoHoras { get; set; }
    }
}
